Repository canonical-web-and-design/tutorials.ubuntu.com, pull requests merged in 2018-06, with the labels that each got.

#763 147 update icons
  .github/PULL_REQUEST_TEMPLATE.md
  images/Helpful-no-24px.svg
  images/Helpful-unsure-24px.svg
  images/Helpful-yes-24px.svg
  src/elements/tutorial-feedback.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#768 Juju Charm development (part 1)
  tutorials/cloud/charm-dev/charm-dev-part1.md
  tutorials/cloud/charm-dev/images/01_charm-store.png
Labels: Don't merge

#755 Graphical Snaps for Ubuntu Core
  tutorials/iot/graphical-snaps/graphical-snaps-xwayland.md
  tutorials/iot/graphical-snaps/graphical-snaps.md
  tutorials/iot/graphical-snaps/images/graphical-snaps-with-mir.png
Labels: Tutorials Content
