Repository canonical-web-and-design/tutorials.ubuntu.com, pull requests merged in 2019-06, with the labels that each got.

#988 Fix ONLYOFFICE tutorial
  tutorials/desktop/how-to-install-onlyoffice/how-to-Install-onlyoffice-desktop-editors-on-ubuntu-18.04.md
Labels: Review: Code +1, Review: QA needed

#989 Update dockerfile from xenial to bionic
  .circleci/config.yml
  Dockerfile
  entrypoint
  package.json
Labels: Review: Code +1, Review: QA +1

#990 Use default npm and nodejs from bionic
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#998 Updates in microk8s for v1.15
  tutorials/containers/install-a-local-kubernetes-with-microk8s/install-a-local-kubernetes-with-microk8s.md
Labels: Review: Code +1

#972 [iot] update kiosk guide to reflect snapd/snapcraft changes
  tutorials/iot/ubuntu-kiosk/electron-kiosk.md
  tutorials/iot/ubuntu-kiosk/secure-ubuntu-kiosk.md
  tutorials/iot/ubuntu-kiosk/ubuntu-web-kiosk.md
  tutorials/iot/ubuntu-kiosk/wayland-kiosk.md
  tutorials/iot/ubuntu-kiosk/x11-kiosk.md
Labels: Tutorials Content
